### ISSUE TITLE
有人愿意加入这个项目的维护吗？

### ISSUE THREAD

**Issue by wolfg1969** [wolfg1969/rack-weixin#8]
现在不玩Ruby，也不玩微信，跟不上变化了。有兴趣的同学留个言吧。

**Comment by anlijiu** [comment]
rails 可以用这个gem 么？ 倒是想加入， 不过ruby 初学者， 能力有限。。

**Comment by wolfg1969** [comment]
@anlijiu 可以用于Rails，虽然我没试过。http://guides.rubyonrails.org/rails_on_rack.html

不妨加个和rails结合的例子，这样你就加入了。

**Comment by iniciontingookou** [comment]
我有兴趣维护rack-weixin。不过我会重构代码，让rack-weixin能够支持多个微信公众号。
https://github.com/wolfg1969/rack-weixin/pull/10

**Comment by wolfg1969** [comment]
@iniciontingookou 好啊，没有问题。
